### ISSUE TITLE
404 page does not appear when incorrect URL is entered.

### ISSUE THREAD

**Issue by DamiDoop** [rvtr/rmc_website#8]
404.html does not appear when you incorrectly enter a URL. 

To reproduce, enter a page that does not exist, such as: `https://randommeaninglesscharacters.com/dsidev/gui/`.

The expected behaviour is that it displays `https://randommeaninglesscharacters.com/404.html`. Instead, it shows the default Apache 404 page.

**Comment by rvtr** [comment]
Whoops, I forgot to add that to the .htaccess file. Error pages now work.
